# Generated by Django 5.0.2 on 2024-03-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='movie_id',
            new_name='media_id',
        ),
        migrations.AddField(
            model_name='history',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], default='movie', max_length=5),
        ),
    ]
